### ISSUE TITLE
misstatement

### ISSUE THREAD

**Issue by paultpearson** [richarddmorey/ConfidenceIntervalsFallacy#1]
The statement "a confidence interval is a set of two, fixed numbers" is incorrect.  A confidence interval of nonzero length is an infinite set of points bounded by two fixed numbers.

**Comment by vasishth** [comment]
Hi guys,

I re-read the CIs paper and have some comments, this is a follow up on our
twitter exchange, which ended with Richard calling me anti-intellectual
and, what else was it, unscientific ;). I didn't know how to fit my comment
into 140 characters or whatever the limit is.

The goal of my comment regarding ANOVA was to make it easier to newcomers
to understand what Bayes gives you, and to pre-empt a dismissal from
die-hard frequentists.

The revised version doesn't do what I was suggesting should be in the
paper. Your ANOVA example addresses a parameter estimate I have personally
never computed or cared about, and I suspect most psycholinguists who do
planned experiments would agree with me.

You should mention clearly and upfront, with some discussion and examples,
the fact that when we do a reasonably large 2x2 repeated measures
experiment (for example), and present main effects and interaction means
and SEs, these estimates are usually going to be identical to the Bayesian
LMM estimates (this is identical to the ANOVA). See examples here:

https://github.com/dmbates/RePsychLing

See vignette KBStan.Rmd and compare Stan estimates with lmer.

The reason I am saying that one should be upfront about this is to pre-empt
dismissive comments from anti-Bayesians. These people will say that look,
these proponents of HPDs conveniently omit the fact that the HPDs and CIs
in these frequently occurring types of experiments are identical. Once
someone says that, the newcomer, who is trying to decide whether to shift
to Bayesian methods, is going to say, OK, well, I'm fine then, and they'll
stick to using CIs. It is in this sense that it is actually harmful not to
be upfront about the correspondence between the intervals.

 One can defuse that comment in advance by simply pointing out this fact,
and explaining why it happens---the likelihood is going to dominate when
you have enough data. Then add that the key point is that the CIs do not
have any useful interpretation, whereas HPDs do (of course you mention that
in the paper, I'm saying that one should mention it in the context that I'm
discussing).  This disables an important rhetorical trick for proponents of
CIs. And then one can finish the argument with: if one can easily compute
HPDs, why not do that? It's a question of how to convince people to make
the shift.

On a side note, the bigger CI problem occurring in psycholinguistics is
that people who do reading studies plot CIs over their regions of interests
in their plots, but continue to compute the CIs incorrectly BUT use them to
do inference. E.g., they will compare the means and CIs across conditions,
and if the mean of one condition falls inside the CI of the other, then the
effect is not significant else it is. IIRC Richard has a paper in which is
provides a correct version of the CI calculation, but I don't think anyone
in psycholinguistics even realizes there is a problem with what we
currently do.

best,

## 

Shravan Vasishth
Professor for Psycholinguistics and Neurolinguistics
Department of Linguistics
University of Potsdam, Germany
http://www.ling.uni-potsdam.de/~vasishth
