### ISSUE TITLE
Uniformly most-powerful procedure

### ISSUE THREAD

**Issue by djrobust** [richarddmorey/ConfidenceIntervalsFallacy#4]
This is a really great article and I am looking forward to its publication.

On page 5 in procedure 3 (_The uniformly most-powerful procedure_) one part of the interval is defined by

![eqn](https://cloud.githubusercontent.com/assets/8261687/9362796/7d1560c4-4657-11e5-914d-7e6c1b7759d2.png)

Should one of the x_2 be an x_1?

**Comment by richarddmorey** [comment]
Ah, yes, thanks; I'll fix that!
